### ISSUE TITLE
building w kali linux, errors.

### ISSUE THREAD

**Issue by adouminoo** [extremedevalt/KeyLogger-TokenGrabber-IpGrabber#19]
┌──(adam㉿kali)-[~]
└─$ ls
Desktop  Documents  Downloads  KeyLogger-TokenGrabber-IpGrabber  Music  Pictures  Public  PyPhisher  PySilon-malware  Templates  Videos
                                                                                                                                                                                            
┌──(adam㉿kali)-[~]
└─$ cd KeyLogger-TokenGrabber-IpGrabber 
                                                                                                                                                                                            
┌──(adam㉿kali)-[~/KeyLogger-TokenGrabber-IpGrabber]
└─$ ls
build  dist  README.md  Requirements.txt  tool.py  tool.spec
                                                                                                                                                                                            
┌──(adam㉿kali)-[~/KeyLogger-TokenGrabber-IpGrabber]
└─$ pyinstaller --onefile tool.py      
314 INFO: PyInstaller: 3.5+498e6ee058
314 INFO: Python: 3.10.8
315 INFO: Platform: Linux-6.0.0-kali3-amd64-x86_64-with-glibc2.36
315 INFO: wrote /home/adam/KeyLogger-TokenGrabber-IpGrabber/tool.spec
317 INFO: UPX is available.
317 INFO: Extending PYTHONPATH with paths
['/home/adam/KeyLogger-TokenGrabber-IpGrabber',
 '/home/adam/KeyLogger-TokenGrabber-IpGrabber']
317 INFO: checking Analysis
317 INFO: Building Analysis because Analysis-00.toc is non existent
317 INFO: Initializing module dependency graph...
322 INFO: Initializing module graph hooks...
322 INFO: Analyzing base_library.zip ...
4792 INFO: Processing pre-find module path hook   distutils
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/adam/KeyLogger-TokenGrabber-IpGrabber/tool.spec", line 6, in <module>
    a = Analysis(['tool.py'],
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 348, in assemble
    self.graph = initialize_modgraph(
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/analysis.py", line 613, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1473, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1657, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale

already edited the tool.py file

**Comment by neos000** [comment]
_bootlocale was removed from cPython 3.10
